---
- hosts: localhost
  connection: local

  tasks:
  - name: Get Key Vault by name
    azure.azcollection.azure_rm_keyvault_info:
      resource_group: dhageman
      name: "kv-meshtest"
      auth_source: msi
    register: keyvault

  - name: Print the Key Vault information
    ansible.builtin.debug:
      var: keyvault


  # - name: Set key vault URI fact
  #   set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  # - name: Set key vault secret fact
  #   set_fact: secretValue={{ lookup('azure_keyvault_secret',secret_name,vault_url=keyvaulturi, client_id=client_id, secret=client_secret, tenant_id=tenant_id) }}

  # - name: Output key vault secret
  #   debug:
  #     msg: "{{ secretValue }}"