---
- name: Example of Automation Mesh with Cloud Native Credentials

  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:

    - name: Get Key Vault by Name
      azure.azcollection.azure_rm_keyvault_info:
        resource_group: dhageman
        name: "kv-meshtest"
        auth_source: msi
      register: keyvault

    - name: Print the Key Vault information
      ansible.builtin.debug:
        var: keyvault

    - name: Set Key Vault url as a fact
      ansible.builtin.set_fact:
        keyvault_url="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

    - name: Use a lookup to get the example secret
      ansible.builtin.set_fact:
        secret_value="{{ lookup('azure.azcollection.azure_keyvault_secret',
                                'ansible-on-azure-secret-credential', vault_url=keyvault_url) }}"

    - name: Output secret retrieved from the Key Vault (NOT RECOMMENDED!)
      ansible.builtin.debug:
        msg: "{{ secret_value }}"
